### ISSUE TITLE
Add *all* contributors to Northstar

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarTF#4]
On the credits page (https://northstar.tf/credits/), using GitHub API we should query for all contributions ever made to Northstar and then list their profiles there, maybe ranked by some metric (commits, line of code changed, ...).

The current list should stay and be on top as a sort of special highlight.

**Comment by TH3-S4LM0N** [comment]
This should also include mod managers and stuff (tho not r2mm) with less priority, as ppl get contrib on discord for it

**Comment by GeckoEidechse** [comment]
Given that we now have https://github.com/R2NorthstarTools/ I think we could also query that next to https://github.com/R2Northstar/ for contributors ^^

**Comment by headassbtw** [comment]
i personally disagree with the R2NorthstarTools stuff, as it doesn't clearly state who's responsible, in the same way `https://github.com/headassbtw/mdlshit` would, kind of a hard problem to solve
as a supplemental thing though, sure, just not the only way to query contribs

**Comment by GeckoEidechse** [comment]
Just to prevent any misunderstandings, the suggested idea would be to have

- **Section: Contributors**
  - Handpicked/hardcoded contributors (what we have right now)
    - These have subtexts with name and area of activity (like it is right now)
- **Section: Community**
  - API scrapped contributors
    - Just profile pic
    - scraped from R2Northstar and R2Northtartools
    - unordered or ordered by some metric (alphabetical, nr of commits, ...)
    - maybe with exclusion for people already mentioned in section above

For the _community_ part we could even add additional repos/orgs that didn't move over to tools but still are an important part of Northstar modding, e.g. https://github.com/MRVN-Radiant ^^

**Comment by barnabwhy** [comment]
is this closable now since the github contributors are now automatically updated and translators is tracked in #76 ?

**Comment by GeckoEidechse** [comment]
Yup, good catch, thanks <3

Closing as completed via #45, #84, and #85
